### ISSUE TITLE
Test failure

### ISSUE THREAD

**Issue by remicollet** [php-ds/tests#3]
There was 1 failure:
1) Warning
The data provider specified for Ds\Tests\MapTest::testSorted is invalid.
Method sortDataProvider does not exist
FAILURES!

Probably Map/sorted could be dropped (seems a duplicate of Map/sort), or the data provider name fixed.

**Comment by rtheunissen** [comment]
The trait for `sort` should have covered this mistake. What version of PHPUnit were you using? Was this when running all the tests?

Fixed in d53ada11733df2284505bc355a0fae40d426ead2

**Comment by remicollet** [comment]
> Was this when running all the tests?

Yes

But this appear only in some cases, probably related to files order (and to classmap used, generated by "phpab" instead of the composer one).

**Comment by remicollet** [comment]
still some duplicate 

```
$ phpab --output foo.php vendor/php-ds/tests/tests/
phpab 1.21.0 - Copyright (C) 2009 - 2016 by Arne Blankerts

Scanning directory vendor/php-ds/tests/tests/
Redeclaration of trait, interface or class found:

    Unit name: ds\tests\map\sort
    First occurance: /work/GIT/php-ds/vendor/php-ds/tests/tests/Map/sorted.php
    Redeclaration: /work/GIT/php-ds/vendor/php-ds/tests/tests/Map/sort.php

```

Even if composer is silent, this could obviously raise some issues.

**Comment by rtheunissen** [comment]
Okay, this should now be fixed in 6bed9cfe04d35f9fe857a430dcecdac2a651ccdc

**Comment by remicollet** [comment]
Another issue:
```
There were 4 errors:

1) Ds\Tests\MapTest::testApply with data set #0 (array(), Closure Object (...))
Error: Call to undefined method Ds\Map::apply()

/dev/shm/BUILD/php-pecl-ds-1.0.1/tests/tests/Map/apply.php:23

2) Ds\Tests\MapTest::testApply with data set #1 (array(1, 2, 3), Closure Object (...))
Error: Call to undefined method Ds\Map::apply()

/dev/shm/BUILD/php-pecl-ds-1.0.1/tests/tests/Map/apply.php:23

3) Ds\Tests\MapTest::testApplyCallbackThrowsException
Error: Call to undefined method Ds\Map::apply()

/dev/shm/BUILD/php-pecl-ds-1.0.1/tests/tests/Map/apply.php:34

4) Ds\Tests\MapTest::testApplyCallbackThrowsExceptionLaterOn
Error: Call to undefined method Ds\Map::apply()

```

**Comment by remicollet** [comment]
Indeed, fixed.

**Comment by rtheunissen** [comment]
Thanks for your help @remicollet
